version: '3'

services:
  syllabus:
    build:
      context: .
      dockerfile: Dockerfile
    command: jupyter notebook --ip 0.0.0.0 --port 8888 --no-browser
    ports:
      - "8888:8888"
    volumes:
      - .:/code
      - vscode-syllabus:/root/.vscode-server
    container_name: syllabus
    # links:
    #   - canned

  canned:
    build:
      context: ./canned
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./canned/responses:/responses

volumes:
  vscode-syllabus:
